services:
  - type: web
    name: hydra-node-render
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
  - type: web
    name: hydra-relay-r2
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
  - type: web
    name: hydra-relay-r3
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
  - type: web
    name: hydra-relay-r4
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
  - type: web
    name: hydra-relay-r5
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
